export enum IBigFivePersonalityTraitType {
    OPENNESS = 'OPENNESS',
    CONSCIENTIOUSNESS = 'CONSCIENTIOUSNESS',
    EXTRAVERSION = 'EXTRAVERSION',
    AGREEABLENESS = 'AGREEABLENESS',
    NEUROTICISM = 'NEUROTICISM'
}
