export enum TraitAttribute {
    INFLUENCE = 'INFLUENCE',
    SOCIABILITY = 'SOCIABILITY',
    CONSISTENCY = 'CONSISTENCY',
    PRECISION = 'PRECISION',
    INTENSITY = 'INTENSITY',
    ABSTRACTION = 'ABSTRACTION',
    PROSOCIAL = 'PROSOCIAL',
    EMOTIONAL_RESONANCE = 'EMOTIONAL_RESONANCE'
}